apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mosquitto-cert
  namespace: {{index . "namespace"}}
spec:
  dnsNames:
    - mosquitto.{{ index . "domain"}}
  secretName: mosquitto-cert
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
