apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  namespace: {{ index . "namespace" }}
data:
  mosquitto.conf: |
    listener 1883
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
    allow_anonymous false
    password_file /mosquitto/config/password.txt
  
  password.txt: |
    admin:$7$101$AKOBw7sRgjlVbIHp$3JRtCzk4rkHl8qGspjcEKhzHyh9VIaqu2BvUfGk0i0eaSOno4l8s7Z9VamTunWgQ+zRSVwWdlGnom8QHlOTSwg==

